name: Deploy to Server

on:
  push:
    branches:
      - master  # Ensure this matches your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Test SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.SERVER_IP }} "echo 'SSH connection successful'"

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          # Change ownership and set permissions
          sudo chown -R azureuser:azureuser /var/www/html/server-admin-vps
          sudo chmod -R u+rwX /var/www/html/server-admin-vps

          # Navigate to project folder and pull latest changes
          cd /var/www/html/server-admin-vps
          git pull origin master
        EOF